title: 谢岗福易门业--品牌不锈钢门、实木门品牌厂家直销
subtitle: "恒久品质，安全保障"
description: "谢岗福易门业主营产品：不锈钢门、实木门、室内门、卫生间门、房间门、防盗门、生态门、高档别墅门等门窗产品，订购电话：13717323108。"
author: 老表
language: zh-cn
timezone: UTC

url: http://www.dgmcd.net
root: /
permalink: news/:year/:month/:day/:title/
archive_dir: news
code_dir: downloads/code
new_post_name: :year-:month-:day-:title.md # File name of new posts
post_asset_folder: true
per_page: 0

theme: navy
deploy:
  type: git
  repo: git@github.com:hexojs/hexojs.github.io.git

highlight:
  enable: true
  line_number: false


