<footer id="footer" class="wrapper">
  <div class="inner">
    <div id="footer-copyright">
      &copy; {{ moment(Date.now()).year() }} <a>谢岗福易门业</a><br>
      <a>Powered by</a><a href="https://github.com/hexojs/hexo/graphs/contributors" target="_blank">Hexo</a>&<a href="http://www.github.com" target="_blank">github</a>&<a href="http://www.netlify.com" target="_blank">Netlify</a>.
      
   </div>
    <div id="footer-links">
    <a>技术支持：</a><a href="http://www.dongkuaiji.com" target="_blank">学会计懂会计</a>
    </div>
  </div>
</footer>
