<footer id="footer" class="wrapper">
  <div class="inner">
    <div id="footer-copyright">
      &copy; {{ moment(Date.now()).year() }} <a>谢岗福易门业</a><br>
      <a>Powered by</a><a href="https://github.com/hexojs/hexo/graphs/contributors" target="_blank">Hexo</a>  &  <a href="http://www.github.com" target="_blank">GitHub</a>  &  <a href="http://www.netlify.com" target="_blank">Netlify</a>.</br>
      <a>技术支持：</a><a href="http://www.dongkuaiji.com" target="_blank">学会计懂会计</a>
   </div>
    <div id="footer-links">
  
    
     <a href="http://www.dgmcd.net/api/console.html" target="_blank">谢岗不锈钢门</a>  |  <a href="http://www.dgmcd.net/api/deployer.html" target="_blank">樟木头不锈钢门</a>  |  <a href="http://www.dgmcd.net/api/filter.html" target="_blank">常平不锈钢门</a><br>
     <a href="http://www.dgmcd.net/api/generator.html" target="_blank">清溪不锈钢门</a>  |  <a href="http://www.dgmcd.net/api/helper.html" target="_blank">沥林不锈钢门</a>  |  <a href="http://www.dgmcd.net/api/migrator.html" target="_blank">桥头不锈钢门</a> 
    </div>
  </div>
</footer>
